( juby
    (set self ryan (new Person))
    (set (get self ryan) first_name 'ryan')
    (set (get self ryan) last_name 'delaney')
    (set (get self ryan) likes 'programming, pizza, etc')
    (delete self ryan)
    (set self ryan (new Person))
    (set (get self ryan) first_name 'ryan')
    (set (get self ryan) last_name 'delaney')
    (set (get self ryan) likes 'programming, pizza, etc')
    (panic someone please help!)
    (set self a 5)
    recover
    (set self b 8)
    (print self)
)
